document.addEventListener('DOMContentLoaded',()=>{
 const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const reveals=document.querySelectorAll('.reveal');
 if('IntersectionObserver' in window&&!reduce){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1});reveals.forEach(x=>io.observe(x))}else reveals.forEach(x=>x.classList.add('visible'));
 const canvas=document.getElementById('network');
 if(canvas){const ctx=canvas.getContext('2d');let nodes=[];const resize=()=>{const r=Math.max(1,devicePixelRatio||1),w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*r;canvas.height=h*r;ctx.setTransform(r,0,0,r,0,0);nodes=Array.from({length:Math.min(64,Math.max(24,Math.floor(w/18)))},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18}))};const draw=()=>{const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);nodes.forEach(n=>{n.x+=n.vx;n.y+=n.vy;if(n.x<0||n.x>w)n.vx*=-1;if(n.y<0||n.y>h)n.vy*=-1;ctx.fillStyle='rgba(103,206,255,.58)';ctx.beginPath();ctx.arc(n.x,n.y,1.35,0,Math.PI*2);ctx.fill()});for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<135){ctx.strokeStyle=`rgba(65,158,255,${.16*(1-d/135)})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}if(!reduce)requestAnimationFrame(draw)};resize();addEventListener('resize',resize);draw()}
 const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');if(toggle&&nav){toggle.addEventListener('click',()=>{nav.classList.toggle('open');toggle.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
 const dlg=document.getElementById('lightbox'),dlgImg=dlg?.querySelector('img');document.querySelectorAll('[data-lightbox]').forEach(b=>b.addEventListener('click',()=>{dlgImg.src=b.dataset.lightbox;dlg.showModal()}));dlg?.querySelector('.dialog-close')?.addEventListener('click',()=>dlg.close());dlg?.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});
});
